name: CD VM(ARM) + Config(Ansible)

on:
  push:
    branches: [ main ]



jobs:
  
  deploy:
    
    runs-on: ubuntu-latest

    
    steps:

    - name: Azure Login Az Cli
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    
    - name: Azure CLI script Creation d'un "Resource Group"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.9.0
        inlineScript: |
          az group create --name ${{ secrets.AZURE_RG }} --location ${{ secrets.AZURE_LOCATION }}