name: CD Site Web

on:
  push:
    branches: [ main ]
    paths:
    - "Playbook_Ansible/**"


jobs:
  
  deploy:
    name: Playbook Ansible
    runs-on: ubuntu-latest

    steps:

    - name: Recuperation des sources - Git
      uses: actions/checkout@master

    - name: Set ssh
      run: |
        mkdir ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa        
        echo "StrictHostKeyChecking no" > ~/.ssh/config
        echo > ~/.ssh/known_hosts        
        chmod 700 ~/.ssh/
        chmod 600 ~/.ssh/*
        sudo sed -i "s/#host_key_checking = False/host_key_checking = False/" /etc/ansible/ansible.cfg        
        ansible -i hosts.yml all -m ping -u pierrc        
      
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}